# Generated by Django 5.2.6 on 2025-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaTCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('fecha', models.DateField()),
                ('juego', models.CharField(choices=[('pokemon', 'Pokémon TCG'), ('yugioh', 'Yu-Gi-Oh!'), ('mitos', 'Mitos y Leyendas'), ('otros', 'Otros')], max_length=50)),
                ('tipo_evento', models.CharField(choices=[('torneo', 'Torneo'), ('lanzamiento', 'Lanzamiento'), ('actualizacion', 'Actualización'), ('comunidad', 'Comunidad')], max_length=50)),
                ('fuente', models.URLField()),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
