# Generated by Django 5.2.6 on 2025-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiatcg',
            name='juego',
            field=models.CharField(choices=[('pokemon', 'Pokémon TCG'), ('yugioh', 'Yu-Gi-Oh!'), ('mitosyleyendas', 'Mitos y Leyendas'), ('otros', 'Otros')], max_length=50),
        ),
    ]
